export const BIRTHDAY_LIST_REQUEST = 'BIRTHDAY_LIST_REQUEST';
export const BIRTHDAY_LIST_SUCCESS = 'BIRTHDAY_LIST_SUCCESS';
export const BIRTHDAY_LIST_FAIL = 'BIRTHDAY_LIST_FAIL';

export const CREATE_BIRTHDAY_REQUEST = 'CREATE_BIRTHDAY_REQUEST';
export const CREATE_BIRTHDAY_SUCCESS = 'CREATE_BIRTHDAY_SUCCESS';
export const CREATE_BIRTHDAY_FAIL = 'CREATE_BIRTHDAY_FAIL';

export const BIRTHDAY_DETAILS_REQUEST = 'BIRTHDAY_DETAILS_REQUEST';
export const BIRTHDAY_DETAILS_SUCCESS = 'BIRTHDAY_DETAILS_SUCCESS';
export const BIRTHDAY_DETAILS_FAIL = 'BIRTHDAY_DETAILS_FAIL';

export const LATEST_BIRTHDAY_REQUEST = 'LATEST_BIRTHDAY_REQUEST';
export const LATEST_BIRTHDAY_SUCCESS = 'LATEST_BIRTHDAY_SUCCESS';
export const LATEST_BIRTHDAY_FAIL = 'LATEST_BIRTHDAY_FAIL';

export const DELETE_BIRTHDAY_REQUEST = 'DELETE_BIRTHDAY_REQUEST';
export const DELETE_BIRTHDAY_SUCCESS = 'DELETE_BIRTHDAY_SUCCESS';
export const DELETE_BIRTHDAY_FAIL = 'DELETE_BIRTHDAY_FAIL';
