export const BIRTHDAY_LIST_REQUEST = 'BIRTHDAY_LIST_REQUEST';
export const BIRTHDAY_LIST_SUCCESS = 'BIRTHDAY_LIST_SUCCESS';
export const BIRTHDAY_LIST_FAIL = 'BIRTHDAY_LIST_FAIL';

export const CREATE_BIRTHDAY_REQUEST = 'CREATE_BIRTHDAY_REQUEST';
export const CREATE_BIRTHDAY_SUCCESS = 'CREATE_BIRTHDAY_SUCCESS';
export const CREATE_BIRTHDAY_FAIL = 'CREATE_BIRTHDAY_FAIL';
